server:
  port: 8081
spring:
  ai:
    mcp:
      client:
        enabled: true
        type: SYNC
        name: elastic-mcp-client
        version: 1.0.0
        sse:
          connections:
            elastic-es:
              url: http://localhost:8080
              sse-endpoint: /mcp
