server:
  port: 8081
spring:
  ai:
    mcp:
      client:
        enabled: true
        type: SYNC
        name: elastic-mcp-client
        version: 1.0.0
        http:
          connections:
            elastic-es:
              url: http://localhost:8080
              endpoint: /mcp
logging:
  level:
    io.modelcontextprotocol: DEBUG
    org.springframework.ai.mcp: DEBUG